version: '3'
services:
  dew:
    image: dew
    container_name: dew
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/usr/src/dew
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ../../public:/data/public
      - ../../../shared:/shared
    ports:
      - "3002:3002"
    expose:
      - 3002
    environment:
      DEPLOY_RUNNER: ${CURRENT_UID:-1}
      APACHE_RUN_USER: "#${CURRENT_UID:-1}"
networks:
  default:
    external:
      name: staging_network